<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>f2bfdfaa-2436-48c2-a752-989e5fe2af87</UserSecretsId>
  </PropertyGroup>

<ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<ProjectReference Include="..\Scraper.Core\Scraper.Core.csproj" />
	<ProjectReference Include="..\Scraper.Parsing\Scraper.Parsing.csproj" />
</ItemGroup>

</Project>
